site_name: 🤖 Inteligencia Artificial (ymorgil)
site_url: https://ymorgil.github.io/intart/

theme:
   name: material
   language: es
   #logo: assets/favicon.svg
   palette:
      - scheme: default
        primary: deep purple
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: teal
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Prompts: 01prompts.md
   - Top: 02top.md
   - Claude: 03claude.md
   - NotebookLM: 04notebook.md
   - Moodle: 05moodle.md
   - Imágenes: 06imagenes.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css

markdown_extensions:
   - attr_list
   - pymdownx.highlight:
        anchor_linenums: false
        use_pygments: true
   - pymdownx.superfences
   - pymdownx.inlinehilite
